org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C\:\\Program Files\\JetBrains\\IntelliJ IDEA 2026.1.1\\jbr

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.17.3
loom_version=1.15-SNAPSHOT

mod_version=1.0.0
maven_group=com.minecraftoverlay
archives_base_name=minecraftoverlay
fabric_api_version=0.141.2+1.21.11
mcef_modern_version=0.3.2+mc1.21.11.jcef143.0.14